version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:16-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-deps-{{ checksum "yarn.lock" }}
            - yarn-deps
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          key: yarn-deps-{{ checksum "yarn.lock" }}-{{ epoch }}
          paths:
            - node_modules
      - run:
          name: Build
          command: |
            if [ $CIRCLE_BRANCH = 'circleci-project-setup' ]; then
              yarn build
            fi
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy:
    working_directory: ~/repo
    docker:
      - image: innovatorjapan/awscli:latest
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Deploy
          command: |
            if [ $CIRCLE_BRANCH = 'circleci-project-setup' ]; then
              aws s3 sync build s3://react.webpack --delete --exact-timestamps;
            fi
workflows:
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - circleci-project-setup
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - circleci-project-setup